added new db management more testing and more

diff --git a/go_boilerplate/Makefile b/go_boilerplate/Makefile
--- a/go_boilerplate/Makefile
+++ b/go_boilerplate/Makefile
@@ -1,3 +1,9 @@
+# Load .env file if it exists
+ifneq (,$(wildcard ./.env))
+    include .env
+    export
+endif
+
 # Project configuration
 PROJECT_NAME := go_boilerplate
 DB_CONTAINER := db_container
@@ -19,11 +25,54 @@ help: ## Show this help message
 # Commands
 .PHONY: test
 test: ## Run all tests
-	go test ./...
+	go test -v -race -bench=. -benchmem ./...
+
+.PHONY: coverage
+coverage: ## Run tests with coverage
+	go test -race -count=3 -timeout=30m  -bench=. -benchmem -coverprofile=coverage.out ./...
+	go tool cover -html=coverage.out
 
 .PHONY: dev
 dev: ## Run the app in development mode using Air
 	air
+
+.PHONY: initdb
+initdb: ## Run the app in production mode
+	migrate create -ext sql -dir sql/migrations -seq init_schema
+
+# Apply database migrations
+.PHONY: migrate-up
+migrate-up:
+	@if [ -z "$(DSN)" ]; then \
+		echo "Error: DSN environment variable not set"; \
+		exit 1; \
+	fi
+	migrate -path sql/migrations -database $(DSN) up
+
+# Revert database migrations
+.PHONY: migrate-down
+migrate-down:
+	@if [ -z "$(DSN)" ]; then \
+		echo "Error: DSN environment variable not set"; \
+		exit 1; \
+	fi
+	migrate -path sql/migrations -database $(DSN) down
+
+.PHONY: migrate-new
+migrate-new: ## Create a new migration (Usage: make migrate-new NAME=<migration_name>)
+	@if [ -z "$(DSN)" ]; then \
+		echo "Error: DSN environment variable not set"; \
+		exit 1; \
+	fi
+	@if [ -z "$(NAME)" ]; then \
+		echo "Usage: make migrate-new NAME=<migration_name>"; \
+		exit 1; \
+	fi
+	migrate create -ext sql -dir sql/migrations -seq $(NAME)
+
+.PHONY: sql
+sql:
+	sqlc generate
 
 .PHONY: db
 db: ## Connect to the local development database
@@ -33,6 +82,11 @@ db: ## Connect to the local development database
 build: ## Build the Docker image
 	docker buildx build -t $(IMAGE_NAME) .
 	docker save $(IMAGE_NAME) > $(PROJECT_NAME).tar
+	trivy image $(IMAGE_NAME)
+
+.PHONY: vulns
+vulns: ## Scan the Docker image for vulnerabilities
+	./scripts/pentest.sh
 
 .PHONY: run
 run: ## Run the app (non-development mode)
@@ -60,19 +114,13 @@ fmt: ## Format the code
 vet: ## Analyze code for potential issues
 	go vet ./...
 
-# Add this to your existing Makefile
-.PHONY: coverage
-coverage: ## Run tests with coverage
-	go test -coverprofile=coverage.out ./...
-	go tool cover -func=coverage.out
-
 .PHONY: ci
 ci: test lint vet fmt coverage ## Run all checks (tests, lint, vet, format)
 
 .PHONY: staging
 staging: ## Deploy to staging environment
-	scp $(PROJECT_NAME).tar docker-compose.yml $(SERVER_STAGING):~/apps/$(PROJECT_NAME)
+	scp $(PROJECT_NAME).tar docker-compose.yml dbp.env $(SERVER_STAGING):~/apps/$(PROJECT_NAME)
 
 .PHONY: production
 production: ## Deploy to production environment
-	scp $(PROJECT_NAME).tar docker-compose.yml $(SERVER_PRODUCTION):~/apps/$(PROJECT_NAME)
+	scp $(PROJECT_NAME).tar $(SERVER_PRODUCTION):~/apps/$(PROJECT_NAME)
